### ISSUE TITLE
Request for 'Obscure text' feature

### ISSUE THREAD

**Issue by dante-teo** [Rahiche/flutter_code_input#11]
Thanks to Rahiche created CodeInput, very appreciate.
Btw I'm here to requesting the feature of 'obscure text', that's quick important for someone to implement 'passcode unlock' behavior.

**Comment by marcelgarus** [comment]
Hi there!
What you're trying to do is actually quite easy to achieve by providing a custom builder, like this:
```dart
CodeInput(
  length: 4,
  keyboardType: TextInputType.number,
  builder: (bool hasFocus, String char) => Container(
    width: 20,
    height: 20,
    color: char.length == 0 ? Colors.black : Colors.white
  ),
  onFilled: (value) => print('Your input is $value.'),
)
```
Now, I'm not sure whether this is a requirement that's common enough for us to include it in this library (i.e. as an `ObscureInputBuilder`)... :thinking:

**Comment by dante-teo** [comment]
Hi, I already did it a few days, I just place an icon inside the container to achieve what I need, just like the below screenshot. (please ignore the funny icon that I choose)
<img width="316" alt="screen shot 2019-01-06 at 8 30 57 am" src="https://user-images.githubusercontent.com/42310298/50730661-a9e61580-118d-11e9-87cf-96b877db0301.png">
Btw thanks for reply, I should study your library before I file this issue, sorry for bothering.
Cheers
