### ISSUE TITLE
[FR] Add ability to provide a FocusNode to the CodeInput widget

### ISSUE THREAD

**Issue by HelgeSverre** [Rahiche/flutter_code_input#14]
I would like to have the ability to provide a FocusNode to the CodeInput widget
So that we can trigger focus on the code input from outside without the user having to interact with it.

This would be useful for login screens where the user is redirected to a code input screen and you want the code input to get focus automatically.

If anyone knows of a workaround, id love some input.

**Comment by Rahiche** [comment]
#15

**Comment by HelgeSverre** [comment]
When will this new feature be available on pub.dev?

**Comment by Rahiche** [comment]
Just updated on pub
Sorry for the delay

**Comment by HelgeSverre** [comment]
Thanks :)
