### ISSUE TITLE
Customize appearance of fields

### ISSUE THREAD

**Issue by pkhivesara** [Rahiche/flutter_code_input#21]
Is there any way to customize the appearance of the fields? For example, I want to remove the border and also change the background color when the field has been filled.

**Comment by pkhivesara** [comment]
@marcelgarus  Any input as how can i achieve the padding with the code in the comment above?
Thanks!

**Comment by marcelgarus** [comment]
Oh sorry, you can of course change the `totalSize` parameter to, let's say `70`, so one input char always takes up `70` of space, but the actual size (`emtpySize` and `filledSize`) are smaller, so there seems to be padding between them.

**Comment by marcelgarus** [comment]
Although I guess the API is confusing in this case. We should probably provide a `spacing` property to the `CodeInput`.

**Comment by pkhivesara** [comment]
I did try that as a hack and it does work. Not the most ideal way unfortunately. For whatever reason, when using the containerized method, it always ends up aligning to the left.
